export const ADD_FRIEND = 'ADD_FRIEND';
export const SAVE_USER_INFO_GOOGLE = 'SAVE_USER_INFO_GOOGLE';
export const SAVE_USER_INFO_KAKAO = 'SAVE_USER_INFO_KAKAO';
export const ADD_RECORDED_ROUTE = 'ADD_RECORDED_ROUTE';
export const SET_PRE_ROUTE_ITEMS = 'SET_PRE_ROUTE_ITEMS';
export const SET_CONTACT_ITEMS = 'SET_CONTACT_ITEMS';
export const RESET_STATE = 'RESET_STATE';

export const GOOGLE_MAPS_APIKEY = 'AIzaSyCiBqROXrj7009fX49-BxlGpd1NyhIldYA'; 
export const TMAP_MAPS_APIKEY = 'l7xxd873259fd9804fe693601cecb92bd4b7'; 

